/**
 * Adapted from PoDoFo private/FontUtilsAFDKO.cpp.
 * PoDoFo's embedded AFDKO flow is retained; exception paths are converted to bool failure.
 * SPDX-License-Identifier: Apache-2.0
 */
#include "FontUtilsAFDKO.h"
extern "C" {
#include <supportexcept.h>
}
#include <absfont.h>
#include <cffread.h>
#include <cffwrite.h>
#include <ctlshare.h>
#include <t1read.h>
#include <algorithm>
#include <csetjmp>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <vector>
namespace {
#define SIG_PS0 CTL_TAG('%','!',0x00,0x00)
#define SIG_PS1 CTL_TAG('%','A',0x00,0x00)
#define SIG_PS2 CTL_TAG('%','%',0x00,0x00)
#define SIG_PFB ((ctlTag)0x80010000)
#define SIG_CFF ((ctlTag)0x01000000)
#define SIG_OTTO CTL_TAG('O','T','T','O')
enum class StreamType : unsigned char { Read=1,Temporary=2,Append=3 };
struct ReadBuffer { StreamType Type=StreamType::Read; PoDoFo::bufferview Data; size_t Pos=0; };
struct AppendBuffer { StreamType Type=StreamType::Append; PoDoFo::charbuff* Data=nullptr; };
struct TemporaryBuffer { StreamType Type=StreamType::Temporary; PoDoFo::charbuff Data; size_t Pos=0; bool Eof=false; char Cache[BUFSIZ]{}; };
struct ConversionContext;
enum class GlyphSelector { ByTag,ByCid };
using GlyphGetter=bool(*)(ConversionContext*,GlyphSelector,unsigned short);
struct GlyphFilter { int(*OriginalBeg)(abfGlyphCallbacks*,abfGlyphInfo*)=nullptr; void(*OriginalWidth)(abfGlyphCallbacks*,float)=nullptr; std::vector<abfGlyphInfo> Infos; unsigned short OutputCid=0; float Width=0; };
struct ConversionContext {
    ConversionContext(PoDoFo::bufferview src,PoDoFo::charbuff& dst,std::string* error) noexcept:Source{StreamType::Read,src,0},Destination{StreamType::Append,&dst},Error(error){Memory.ctx=this;Memory.manage=&MemoryManage;Streams.direct_ctx=this;Streams.open=&StreamOpen;Streams.seek=&StreamSeek;Streams.tell=&StreamTell;Streams.read=&StreamRead;Streams.xml_read=nullptr;Streams.write=&StreamWrite;Streams.status=&StreamStatus;Streams.close=&StreamClose;}
    ~ConversionContext(){if(T1)t1rFree(T1);if(Cfr)cfrFree(Cfr);if(Cfw)cfwFree(Cfw);}
    void Fail(const char* text) noexcept {Failed=true;if(Error&&Error->empty())*Error=text?text:"AFDKO failure";}
    static void* MemoryManage(ctlMemoryCallbacks*,void* old,size_t size) noexcept {if(size==0){std::free(old);return nullptr;}return std::realloc(old,size);}
    static void* StreamOpen(ctlStreamCallbacks*,int,size_t) noexcept; static int StreamSeek(ctlStreamCallbacks*,void*,long) noexcept; static long StreamTell(ctlStreamCallbacks*,void*) noexcept; static size_t StreamRead(ctlStreamCallbacks*,void*,char**) noexcept; static size_t StreamWrite(ctlStreamCallbacks*,void*,size_t,char*) noexcept; static int StreamStatus(ctlStreamCallbacks*,void*) noexcept; static int StreamClose(ctlStreamCallbacks*,void*) noexcept{return 0;}
    ReadBuffer Source; AppendBuffer Destination; TemporaryBuffer T1Tmp,CfwTmp; std::string* Error=nullptr; bool Failed=false; bool Pfb=false,PfbEof=false; size_t PfbLeft=0; ctlMemoryCallbacks Memory{};ctlStreamCallbacks Streams{};abfGlyphCallbacks Glyph{};t1rCtx T1=nullptr;cfrCtx Cfr=nullptr;cfwCtx Cfw=nullptr;abfTopDict* Top=nullptr;long CfrFlags=0;const PoDoFo::FontMetrics* Metrics=nullptr;PoDoFo::cspan<PoDoFo::FontCharGIDInfo> Infos;const PoDoFo::CIDSystemInfo* CID=nullptr;GlyphFilter Filter;
};
bool readByte(ConversionContext* h,unsigned char& v) noexcept {if(!h||h->Source.Pos>=h->Source.Data.size()){if(h)h->Fail("unexpected end of font data");return false;}v=static_cast<unsigned char>(h->Source.Data[h->Source.Pos++]);return true;}
size_t refillPfb(ConversionContext* h,char** ptr) noexcept {if(!h||!ptr)return 0;while(h->PfbLeft==0){unsigned char escape=0,type=0,b0=0,b1=0,b2=0,b3=0;if(!readByte(h,escape)||!readByte(h,type)){*ptr=nullptr;return 0;}if(escape!=128||(type!=1&&type!=2&&type!=3)){h->Fail("bad PFB segment type");*ptr=nullptr;return 0;}if(type==3){h->PfbEof=true;*ptr=nullptr;return 0;}if(!readByte(h,b0)||!readByte(h,b1)||!readByte(h,b2)||!readByte(h,b3)){*ptr=nullptr;return 0;}h->PfbLeft=static_cast<size_t>(b0)|(static_cast<size_t>(b1)<<8)|(static_cast<size_t>(b2)<<16)|(static_cast<size_t>(b3)<<24);}if(h->Source.Pos>h->Source.Data.size()){h->Fail("PFB source position outside buffer");*ptr=nullptr;return 0;}const auto count=std::min(h->Source.Data.size()-h->Source.Pos,h->PfbLeft);if(count==0){h->Fail("truncated PFB segment");*ptr=nullptr;return 0;}*ptr=const_cast<char*>(h->Source.Data.data()+h->Source.Pos);h->Source.Pos+=count;h->PfbLeft-=count;return count;}
void* ConversionContext::StreamOpen(ctlStreamCallbacks* cb,int id,size_t) noexcept {auto* h=static_cast<ConversionContext*>(cb->direct_ctx);switch(id){case T1R_SRC_STREAM_ID:case CFR_SRC_STREAM_ID:return &h->Source;case CFW_DST_STREAM_ID:return &h->Destination;case T1R_TMP_STREAM_ID:return &h->T1Tmp;case CFW_TMP_STREAM_ID:return &h->CfwTmp;case T1R_DBG_STREAM_ID:case CFR_DBG_STREAM_ID:case CFW_DBG_STREAM_ID:return nullptr;default:h->Fail("AFDKO requested unknown stream");return nullptr;}}
int ConversionContext::StreamSeek(ctlStreamCallbacks* cb,void* stream,long offset) noexcept {if(!stream||offset<0)return -1;auto* h=static_cast<ConversionContext*>(cb->direct_ctx);switch(*static_cast<StreamType*>(stream)){case StreamType::Read:{auto* s=static_cast<ReadBuffer*>(stream);if(static_cast<size_t>(offset)>s->Data.size()){h->Fail("source seek outside buffer");return -1;}s->Pos=static_cast<size_t>(offset);return 0;}case StreamType::Temporary:{auto* s=static_cast<TemporaryBuffer*>(stream);if(static_cast<size_t>(offset)>s->Data.size())s->Data.resize(static_cast<size_t>(offset));s->Pos=static_cast<size_t>(offset);s->Eof=false;return 0;}case StreamType::Append:return -1;}return -1;}
long ConversionContext::StreamTell(ctlStreamCallbacks*,void* stream) noexcept {if(!stream)return -1;switch(*static_cast<StreamType*>(stream)){case StreamType::Read:return static_cast<long>(static_cast<ReadBuffer*>(stream)->Pos);case StreamType::Temporary:return static_cast<long>(static_cast<TemporaryBuffer*>(stream)->Pos);case StreamType::Append:return static_cast<long>(static_cast<AppendBuffer*>(stream)->Data->size());}return -1;}
size_t ConversionContext::StreamRead(ctlStreamCallbacks* cb,void* stream,char** ptr) noexcept {if(!stream||!ptr)return 0;auto* h=static_cast<ConversionContext*>(cb->direct_ctx);switch(*static_cast<StreamType*>(stream)){case StreamType::Read:{auto* s=static_cast<ReadBuffer*>(stream);if(h->Pfb)return refillPfb(h,ptr);if(s->Pos>s->Data.size())return 0;*ptr=const_cast<char*>(s->Data.data()+s->Pos);const auto count=s->Data.size()-s->Pos;s->Pos=s->Data.size();return count;}case StreamType::Temporary:{auto* s=static_cast<TemporaryBuffer*>(stream);*ptr=s->Cache;if(s->Eof||s->Pos>s->Data.size())return 0;const auto count=std::min(sizeof(s->Cache),s->Data.size()-s->Pos);if(count)std::memcpy(s->Cache,s->Data.data()+s->Pos,count);s->Pos+=count;s->Eof=s->Pos==s->Data.size();return count;}case StreamType::Append:return 0;}return 0;}
size_t ConversionContext::StreamWrite(ctlStreamCallbacks*,void* stream,size_t count,char* ptr) noexcept {if(!stream||(!ptr&&count))return 0;switch(*static_cast<StreamType*>(stream)){case StreamType::Temporary:{auto* s=static_cast<TemporaryBuffer*>(stream);if(count>std::numeric_limits<size_t>::max()-s->Pos)return 0;if(s->Pos+count>s->Data.size())s->Data.resize(s->Pos+count);if(count)std::memcpy(s->Data.data()+s->Pos,ptr,count);s->Pos+=count;s->Eof=false;return count;}case StreamType::Append:{auto* s=static_cast<AppendBuffer*>(stream);s->Data->append(ptr,count);return count;}case StreamType::Read:return 0;}return 0;}
int ConversionContext::StreamStatus(ctlStreamCallbacks* cb,void* stream) noexcept {if(!stream)return CTL_STREAM_ERROR;auto* h=static_cast<ConversionContext*>(cb->direct_ctx);if(h->Failed)return CTL_STREAM_ERROR;switch(*static_cast<StreamType*>(stream)){case StreamType::Read:{auto* s=static_cast<ReadBuffer*>(stream);return h->Pfb?(h->PfbEof?CTL_STREAM_END:CTL_STREAM_OK):(s->Pos==s->Data.size()?CTL_STREAM_END:CTL_STREAM_OK);}case StreamType::Temporary:return static_cast<TemporaryBuffer*>(stream)->Eof?CTL_STREAM_END:CTL_STREAM_OK;case StreamType::Append:return CTL_STREAM_OK;}return CTL_STREAM_ERROR;}
bool beginSet(ConversionContext* h) noexcept {if(!h->Cfw){h->Cfw=cfwNew(&h->Memory,&h->Streams,CFW_CHECK_ARGS);if(!h->Cfw){h->Fail("cfwNew failed");return false;}}if(cfwBegSet(h->Cfw,CFW_PRESERVE_GLYPH_ORDER)){h->Fail("cfwBegSet failed");return false;}return true;}
bool beginFont(ConversionContext* h) noexcept {h->Glyph=cfwGlyphCallbacks;h->Glyph.direct_ctx=h->Cfw;h->Glyph.moveVF=nullptr;h->Glyph.lineVF=nullptr;h->Glyph.curveVF=nullptr;h->Glyph.stemVF=nullptr;if(cfwBegFont(h->Cfw,nullptr,0)){h->Fail("cfwBegFont failed");return false;}return true;}
bool endFont(ConversionContext* h) noexcept {if(cfwEndFont(h->Cfw,h->Top)){h->Fail("cfwEndFont failed");return false;}return true;}
bool endSet(ConversionContext* h) noexcept {if(cfwEndSet(h->Cfw)){h->Fail("cfwEndSet failed");return false;}return true;}
int filterBegin(abfGlyphCallbacks* cb,abfGlyphInfo* info) noexcept {auto* f=static_cast<GlyphFilter*>(cb->indirect_ctx);if(!f||!f->OriginalBeg||f->OutputCid>=f->Infos.size())return ABF_FAIL_RET;auto& replacement=f->Infos[f->OutputCid];replacement=*info;replacement.cid=f->OutputCid;replacement.flags|=ABF_GLYPH_CID;replacement.flags&=~ABF_GLYPH_SEEN;replacement.gname.ptr=nullptr;replacement.gname.impl=0;replacement.encoding={};return f->OriginalBeg(cb,&replacement);}
void filterWidth(abfGlyphCallbacks* cb,float) noexcept {auto* f=static_cast<GlyphFilter*>(cb->indirect_ctx);if(f&&f->OriginalWidth)f->OriginalWidth(cb,f->Width);}
bool getCffGlyph(ConversionContext* h,GlyphSelector s,unsigned short id) noexcept {const int rc=s==GlyphSelector::ByCid?cfrGetGlyphByCID(h->Cfr,id,&h->Glyph):cfrGetGlyphByTag(h->Cfr,id,&h->Glyph);if(rc){h->Fail("cfrGetGlyph failed");return false;}return true;}
bool getT1Glyph(ConversionContext* h,GlyphSelector s,unsigned short id) noexcept {const int rc=s==GlyphSelector::ByCid?t1rGetGlyphByCID(h->T1,id,&h->Glyph):t1rGetGlyphByTag(h->T1,id,&h->Glyph);if(rc){h->Fail("t1rGetGlyph failed");return false;}return true;}
bool emitSubset(ConversionContext* h,GlyphGetter get) noexcept {if(!h->Metrics||!h->CID)return false;h->Top->sup.flags|=ABF_CID_FONT;h->Top->cid.Registry.ptr=const_cast<char*>(h->CID->Registry.c_str());h->Top->cid.Ordering.ptr=const_cast<char*>(h->CID->Ordering.c_str());h->Top->cid.Supplement=h->CID->Supplement;h->Filter.OriginalBeg=h->Glyph.beg;h->Filter.OriginalWidth=h->Glyph.width;h->Glyph.beg=&filterBegin;h->Glyph.width=&filterWidth;h->Glyph.indirect_ctx=&h->Filter;unsigned short maxCid=0;for(const auto& info:h->Infos)maxCid=std::max(maxCid,info.Cid);h->Filter.Infos.resize(static_cast<size_t>(maxCid)+1u);const bool sourceCid=h->Metrics->GetFontFileType()==PoDoFo::FontFileType::CIDKeyedCFF;const auto selector=sourceCid?GlyphSelector::ByCid:GlyphSelector::ByTag;h->Filter.OutputCid=0;h->Filter.Width=0;if(!get(h,selector,0))return false;for(const auto& info:h->Infos){if(info.Cid==0||info.Gid.Id>0xFFFFu){h->Fail("invalid CFF subset CID/GID");return false;}double width=0;if(!h->Metrics->TryGetGlyphWidthFontProgram(info.Gid.MetricsId,width)){h->Fail("unable to get CFF glyph width");return false;}h->Filter.OutputCid=info.Cid;h->Filter.Width=static_cast<float>(width*h->Metrics->GetUnitsPerEm());if(!get(h,selector,static_cast<unsigned short>(info.Gid.Id)))return false;}return true;}
bool readCff(ConversionContext* h,long origin,int index) noexcept {if(!h->Cfr){h->Cfr=cfrNew(&h->Memory,&h->Streams,CFR_CHECK_ARGS);if(!h->Cfr){h->Fail("cfrNew failed");return false;}}const long flags=h->Metrics?h->CfrFlags|CFR_UPDATE_OPS:h->CfrFlags;if(cfrBegFont(h->Cfr,flags,origin,index,&h->Top,nullptr)){h->Fail("cfrBegFont failed");return false;}if(!beginFont(h))return false;bool ok=h->Metrics?emitSubset(h,&getCffGlyph):cfrIterateGlyphs(h->Cfr,&h->Glyph)==0;if(!ok&&!h->Failed)h->Fail("cfrIterateGlyphs failed");if(ok)ok=endFont(h);if(cfrEndFont(h->Cfr)){h->Fail("cfrEndFont failed");ok=false;}return ok&&!h->Failed;}
bool readT1(ConversionContext* h,long origin) noexcept {if(!h->T1){h->T1=t1rNew(&h->Memory,&h->Streams,T1R_CHECK_ARGS);if(!h->T1){h->Fail("t1rNew failed");return false;}}if(t1rBegFont(h->T1,0,origin,&h->Top,nullptr)){h->Fail("t1rBegFont failed");return false;}if(!beginFont(h))return false;bool ok=h->Metrics?emitSubset(h,&getT1Glyph):t1rIterateGlyphs(h->T1,&h->Glyph)==0;if(!ok&&!h->Failed)h->Fail("t1rIterateGlyphs failed");if(ok)ok=endFont(h);if(t1rEndFont(h->T1)){h->Fail("t1rEndFont failed");ok=false;}return ok&&!h->Failed;}
bool convert(ConversionContext* h) noexcept {if(h->Source.Data.size()<2){h->Fail("font data is too short");return false;}unsigned char a=0,b=0,c=0,d=0;if(!readByte(h,a)||!readByte(h,b))return false;ctlTag sig=static_cast<ctlTag>(a)<<24|static_cast<ctlTag>(b)<<16;if(sig==SIG_PFB){h->Pfb=true;h->Source.Pos=0;return readT1(h,0);}if(sig==SIG_PS0||sig==SIG_PS1||sig==SIG_PS2){h->Source.Pos=0;return readT1(h,0);}if(sig==SIG_CFF){if(!readByte(h,c)||c!=4){h->Fail("unsupported CFF header");return false;}h->Source.Pos=0;return readCff(h,0,0);}if(!readByte(h,c)||!readByte(h,d))return false;sig|=static_cast<ctlTag>(c)<<8|d;if(sig==SIG_OTTO){h->Source.Pos=0;h->CfrFlags|=CFR_NO_ENCODING;return readCff(h,0,0);}h->Fail("AFDKO supports PFA/PFB, raw CFF and OpenType-CFF");return false;}
bool run(PoDoFo::bufferview src,PoDoFo::charbuff& dst,const PoDoFo::FontMetrics* metrics,PoDoFo::cspan<PoDoFo::FontCharGIDInfo> infos,const PoDoFo::CIDSystemInfo* cid,std::string* error) noexcept {dst.clear();if(error)error->clear();if(src.empty()){if(error)*error="AFDKO source is empty";return false;}ConversionContext h(src,dst,error);h.Metrics=metrics;h.Infos=infos;h.CID=cid;if(!beginSet(&h)||!convert(&h)||!endSet(&h)||h.Failed||dst.empty())return false;return true;}
}
namespace afdko {
bool ConvertFontType1ToCFF(const PoDoFo::bufferview& src,PoDoFo::charbuff& dst,std::string* error) noexcept {return run(src,dst,nullptr,{},nullptr,error);}
bool ConvertFontToCFF(const PoDoFo::bufferview& src,PoDoFo::charbuff& dst,std::string* error) noexcept {return run(src,dst,nullptr,{},nullptr,error);}
bool SubsetFontCFF(const PoDoFo::FontMetrics& metrics,const PoDoFo::cspan<PoDoFo::FontCharGIDInfo>& subsetInfos,const PoDoFo::CIDSystemInfo& cidInfo,PoDoFo::charbuff& dstCFF,std::string* error) noexcept {if(subsetInfos.empty()){if(error)*error="CFF glyph list must not be empty";return false;}return run(metrics.GetOrLoadFontFileData(),dstCFF,&metrics,subsetInfos,&cidInfo,error);}
}
extern "C" void os_raise(_Exc_Buf* buf,int code,char* message) {if(!buf)std::abort();buf->Code=code==0?1:code;buf->Message=message;longjmp(buf->Environ,buf->Code);}
